server:
  port: 8081

spring:
  application:
    name: myapp

  datasource:
    url: jdbc:postgresql://localhost:5435/mydatabase
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


